language: node_js
node_js:
        - "stable"
before_install:
        - sudo apt-get install deluged
        - deluged &
        - cd server/
install:
        - npm install
cache:
  directories:
    - "node_modules"
