language: node_js
node_js:
        - "stable"
before_install:
        - sudo apt-get update
        - sudo apt-get upgrade
        - sudo apt-get install deluged
        - sudo systemctl start deluged
        - cd server/
install:
        - npm install
cache:
  directories:
    - "node_modules"
